id: PA085DDA0
initial_creation_type: ocr
source_metadata:
  volumes:
    6c95b3a77ce1400ba4b051f8c0ae5d62:
      base_file: v052.txt
      image_group_id: I1PD95897
      title: མངོན་པར་རྟོགས་པའི་རྒྱན་ཞེས་བྱ་བའི་འགྲེལ་པ་རྟོགས་པར་དཀའ་བའི་སྣང་བ་ཞེས་བྱ་བའི་འགྲེལ་བཤད།
      total_pages: 1426
      volume_number: 52
