id: DA485F376
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-07T14:01:00+00:00'
last_modified: '2022-05-27T05:21:48.022180+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    e0c4:
      image_group_id: I1PD95897
      title: མངོན་པར་རྟོགས་པའི་རྒྱན་ཞེས་བྱ་བའི་འགྲེལ་པ་རྟོགས་པར་དཀའ་བའི་སྣང་བ་ཞེས་བྱ་བའི་འགྲེལ་བཤད།
      total_pages: 1426
      order: 52
      base_file: e0c4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
